テストコードを修正
SakitaDaiki0623/rspec_app_exam pull request #1
Opened 2021-01-23 07:10 UTC by SakitaDaiki0623

## 変更の概要

* `spec/system/task_spec.rb`のテストコードを修正

## テスト実行時のスクリーンショット
```
$ bundle exec rspec spec/system/task_spec.rb
```

[![Image from Gyazo](https://i.gyazo.com/202b3bfaa93726170aad797ddf46f43d.png)](https://gyazo.com/202b3bfaa93726170aad797ddf46f43d)

## 備考

コミット名が「Fix: ~」で始まるものは回答のNG例を元に修正しています。

2021-01-23 08:20 UTC, yuji91 requested changes
修正方針については問題ありません。

細かい点をいくつか指摘したので、修正に対応したコミットIDを返答して頂ければと思います。

2021-01-23 08:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:project) { FactoryBot.create(:project) }
設定ファイルに追記を行うことで省略が可能です。
コードの全体量が減って見通しが良くなるので、積極的に省略していきましょう。
```suggestion
  let(:project) { create(:project) }
```

2021-01-23 08:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { FactoryBot.create(:task, project_id: project.id) }
Factoryにassociationを定義するとproject_idを指定する必要が無くなります。
```suggestion
  let(:task) { create(:task) }
```

2021-01-23 08:20 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :done_task do
taskのtraitなのでtaskという情報はつけなくても良いかなと思いました。
```suggestion
    trait :done do
```

2021-01-23 08:48 UTC, SakitaDaiki0623 commented
各コメントに基づいて修正しましたのでご確認お願いいたします。

また、コードを変更したので再度テストした結果のスクショを添付しておきます。

```
$ bundle exec rspec spec/system/task_spec.rb
```
[![Image from Gyazo](https://i.gyazo.com/6c58432784e6908bda74c23d57158ed4.png)](https://gyazo.com/6c58432784e6908bda74c23d57158ed4)

2021-01-23 12:15 UTC, SakitaDaiki0623 commented on spec/system/task_spec.rb
> +  let(:project) { FactoryBot.create(:project) }
コミットID[201a6d3](https://github.com/SakitaDaiki0623/rspec_app_exam/pull/1/commits/201a6d327c87575c6231e18e571de288d688d63e)で修正しました。

2021-01-23 12:17 UTC, SakitaDaiki0623 commented on spec/system/task_spec.rb
> +  let(:task) { FactoryBot.create(:task, project_id: project.id) }
コミットID[41e9105](https://github.com/SakitaDaiki0623/rspec_app_exam/pull/1/commits/41e9105e1d1d509ec6f7c7368e49b9bcd2c2f1f6)で修正しました。

2021-01-23 12:19 UTC, SakitaDaiki0623 commented on spec/factories/tasks.rb
> +    trait :done_task do
コミットID[a2b19f2](https://github.com/SakitaDaiki0623/rspec_app_exam/pull/1/commits/a2b19f23495b7347c9d368aaef7e89ccbfdd0b5f)で修正しまいた。

2021-01-26 09:25 UTC, yuji91 approved these changes
こちら修正が問題ないことを確認しました。

LGTMです！

2022-01-21 00:37 UTC, closed without merging